### ISSUE TITLE
Validate Plugin works with Corporate JIRA

### ISSUE THREAD

**Issue by sion-smith-lbg** [fourplusone/terraform-provider-jira#66] opened 2022-07-06 09:33 UTC
I am getting the following error when trying to create a basic issue: 
`2022-07-06T10:30:14.711+0100 [INFO]  Starting apply for jira_issue.example
2022-07-06T10:30:14.711+0100 [DEBUG] jira_issue.example: applying the planned Create change
2022-07-06T10:30:14.953+0100 [ERROR] vertex "jira_issue.example" error: creating jira issue failed: : could not unmarshall the data into struct`

Is there a way I can validate is the provider works with a corporate installation?

**Comment by fourplusone** [comment] 2022-07-06 18:03
I think this is a duplicate of #65

**Closed by fourplusone** 2022-07-06 18:03 UTC
